### ISSUE TITLE
mqtt service test is producing a ProtocolException

### ISSUE THREAD

**Issue by jwhitcraft** [github/github-services#1138]
When running the tests on the master branch, they started failing for me with the MQTT
```
  1) Error:
MqttPubTest#test_push:
MQTT::ProtocolException: MQTT::ProtocolException
    /Users/jwhitcraft/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/mqtt-0.0.8/lib/mqtt/packet.rb:238:in `read_byte'
    /Users/jwhitcraft/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/mqtt-0.0.8/lib/mqtt/packet.rb:21:in `read'
    /Users/jwhitcraft/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/mqtt-0.0.8/lib/mqtt/client.rb:301:in `block in receive_connack'
    /Users/jwhitcraft/.rbenv/versions/2.1.7/lib/ruby/2.1.0/timeout.rb:90:in `block in timeout'
    /Users/jwhitcraft/.rbenv/versions/2.1.7/lib/ruby/2.1.0/timeout.rb:33:in `block in catch'
    /Users/jwhitcraft/.rbenv/versions/2.1.7/lib/ruby/2.1.0/timeout.rb:33:in `catch'
    /Users/jwhitcraft/.rbenv/versions/2.1.7/lib/ruby/2.1.0/timeout.rb:33:in `catch'
    /Users/jwhitcraft/.rbenv/versions/2.1.7/lib/ruby/2.1.0/timeout.rb:105:in `timeout'
    /Users/jwhitcraft/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/mqtt-0.0.8/lib/mqtt/client.rb:300:in `receive_connack'
    /Users/jwhitcraft/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/mqtt-0.0.8/lib/mqtt/client.rb:146:in `connect'
    /Users/jwhitcraft/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/mqtt-0.0.8/lib/mqtt/client.rb:50:in `connect'
    /Users/jwhitcraft/Projects/github-services/lib/services/mqtt.rb:58:in `receive_push'
    /Users/jwhitcraft/Projects/github-services/lib/service.rb:693:in `block in receive'
    /Users/jwhitcraft/.rbenv/versions/2.1.7/lib/ruby/2.1.0/timeout.rb:90:in `block in timeout'
    /Users/jwhitcraft/.rbenv/versions/2.1.7/lib/ruby/2.1.0/timeout.rb:100:in `call'
    /Users/jwhitcraft/.rbenv/versions/2.1.7/lib/ruby/2.1.0/timeout.rb:100:in `timeout'
    /Users/jwhitcraft/Projects/github-services/lib/service.rb:692:in `receive'
    /Users/jwhitcraft/Projects/github-services/test/mqtt_test.rb:10:in `test_push'
```

**Comment by jwhitcraft** [comment]
This seems to be happeing becuase q.m2m.io is throwing 503 errors.

**Comment by bswinnerton** [comment]
Thank you for pointing this out, @jwhitcraft! We've begun looking into the failing test.
